const menuButton=document.querySelector('.menu-toggle');const nav=document.querySelector('#site-nav');
menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));});
const entries=[
 {name:'Inner Compass Initiative',category:'informed-choice',label:'Informed choice & withdrawal',description:'Public education on psychiatric diagnoses, drugs, withdrawal, and a peer-to-peer Exchange community.',url:'https://www.theinnercompass.org/'},
 {name:'Benzodiazepine Information Coalition',category:'informed-choice',label:'Drug safety & informed consent',description:'Education and advocacy concerning prescribed benzodiazepines, adverse effects, and informed consent.',url:'https://www.benzoinfo.com/'},
 {name:'Akathisia Alliance for Education and Research',category:'informed-choice',label:'Adverse effects & education',description:'Resources for recognizing akathisia and advancing education and research about the condition.',url:'https://akathisiaalliance.org/'},
 {name:'Inner Compass Exchange',category:'peer-support',label:'Online peer community',description:'A peer-to-peer space for discussion, learning, events, and mutual support.',url:'https://exchange.theinnercompass.org/'},
 {name:'National Empowerment Center',category:'peer-support',label:'Peer support & respite',description:'Peer-led resources, technical assistance, and a directory of peer respite programs.',url:'https://power2u.org/'},
 {name:'Hearing Voices USA',category:'peer-support',label:'Peer groups',description:'Resources and groups for people who hear voices and have other unusual experiences.',url:'https://www.hearingvoicesusa.org/'},
 {name:'Project LETS',category:'peer-support',label:'Community peer support',description:'Peer support collectives and community-based responses to mental distress.',url:'https://projectlets.org/'},
 {name:'RxISK',category:'research',label:'Drug safety & accountability',description:'Independent information and patient reports about potential adverse effects of prescription medicines.',url:'https://rxisk.org/'},
 {name:'Metabolic Mind',category:'approaches',label:'Metabolism & mental health',description:'Education and research resources on emerging metabolic approaches to mental health.',url:'https://www.metabolicmind.org/'}
];
const list=document.querySelector('#directory-list');
if(list){const search=document.querySelector('#directory-search'),count=document.querySelector('#result-count');let active='all';
function render(){const term=search.value.trim().toLowerCase();const matches=entries.filter(e=>(active==='all'||e.category===active)&&`${e.name} ${e.label} ${e.description}`.toLowerCase().includes(term));list.replaceChildren();count.textContent=`${matches.length} ${matches.length===1?'organization':'organizations'} shown`;if(!matches.length){const p=document.createElement('p');p.className='empty-state';p.textContent='No organizations match. Try another term or area of work.';list.append(p);return;}for(const e of matches){const a=document.createElement('article');a.className='directory-entry';a.dataset.category=e.category;const tag=document.createElement('span');tag.className='entry-tag';tag.textContent=e.label;const h=document.createElement('h3');h.textContent=e.name;const p=document.createElement('p');p.textContent=e.description;const link=document.createElement('a');link.href=e.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Visit organization ↗';a.append(tag,h,p,link);list.append(a);}}
document.querySelectorAll('.filters button').forEach(button=>button.addEventListener('click',()=>{active=button.dataset.filter;document.querySelectorAll('.filters button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));render();}));search.addEventListener('input',render);const hash=location.hash.slice(1);if(['informed-choice','peer-support','research','approaches'].includes(hash)){const button=document.querySelector(`.filters button[data-filter="${hash}"]`);button.click();}else render();}
