"""Generate the static Mental Health Hub pages. Run: python build.py"""
from pathlib import Path

ROOT = Path(__file__).parent
DONATE_URL = 'https://givebutter.com/maha-mental-health-gvp1bu'

def ext(url, label, cls='text-link'):
    return f'<a class="{cls}" href="{url}" target="_blank" rel="noopener noreferrer">{label}<span aria-hidden="true">↗</span></a>'

def card(no, eyebrow, title, description, href, action='Explore'):
    return f'''<a class="route-card" href="{href}"><span class="route-no">{no}</span><span class="route-label">{eyebrow}</span><h3>{title}</h3><p>{description}</p><span class="route-action">{action} <span aria-hidden="true">↗</span></span></a>'''

def layout(title, description, active, body):
    links = [('Evidence & options','evidence.html','evidence'),('Support','support.html','support'),('Organizations','organizations.html','organizations'),('Policy','policy.html','policy')]
    nav = ''.join(f'<a href="{url}"{(" aria-current=\"page\"" if key==active else "")}>{label}</a>' for label,url,key in links)
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#153b31"><meta name="description" content="{description}"><title>{title} | MAHA Mental Health Hub</title><link rel="icon" type="image/svg+xml" href="favicon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=Newsreader:opsz,wght@6..72,400;6..72,500;6..72,600&family=Source+Sans+3:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="styles.css"><script src="app.js" defer></script></head>
<body><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="shell header-inner"><a class="wordmark" href="index.html" aria-label="MAHA Mental Health Hub home"><span class="wordmark-main">MAHA<span class="wordmark-slash">/</span>MH</span><span class="wordmark-sub">MENTAL HEALTH HUB</span></a><button class="menu-toggle" type="button" aria-controls="site-nav" aria-expanded="false">Menu <span aria-hidden="true">☰</span></button><nav id="site-nav" aria-label="Main navigation">{nav}<a class="nav-donate" href="{DONATE_URL}" target="_blank" rel="noopener noreferrer">Donate to ICI <span aria-hidden="true">↗</span></a></nav></div></header>
<main id="main">{body}</main>
<footer class="site-footer"><div class="shell"><div class="footer-main"><div><a class="wordmark wordmark-light" href="index.html"><span class="wordmark-main">MAHA<span class="wordmark-slash">/</span>MH</span><span class="wordmark-sub">MENTAL HEALTH HUB</span></a><p>More knowledge. More options. More meaningful choice.</p></div><div class="footer-nav"><div><span class="footer-label">Explore</span><a href="evidence.html">Evidence & options</a><a href="support.html">Peer & community support</a><a href="organizations.html">Organizations</a><a href="policy.html">Policy & advocacy</a></div><div><span class="footer-label">Connect</span><a href="giving.html">About giving</a><a href="https://www.mahacenter.org/" target="_blank" rel="noopener noreferrer">MAHA Center ↗</a><a href="https://www.mahacenter.org/involved" target="_blank" rel="noopener noreferrer">MAHA updates ↗</a></div></div></div><div class="footer-disclaimer"><p>Resources are offered for general education. They are not medical advice, diagnosis, a treatment recommendation, or a personalized tapering plan. Inclusion does not imply agreement with every claim or service from an outside organization. People considering changes to psychiatric medication should seek appropriate support; abrupt changes can carry serious risks.</p></div><div class="footer-bottom"><span>© 2026 MAHA Mental Health Hub</span><a href="index.html#approach">How we select resources</a></div></div></footer></body></html>'''

home = '''
<section class="home-hero"><div class="shell hero-layout"><div class="hero-content"><p class="eyebrow light">MENTAL HEALTH IN AMERICA <span class="eyebrow-line"></span> A DIFFERENT STARTING POINT</p><h1>More knowledge.<br><em>More options.</em><br>More choice.</h1><p class="hero-lead">America is facing widespread distress. Honest answers require room for scientific uncertainty, lived experience, and more than one path to support.</p><div class="hero-actions"><a class="button button-cream" href="evidence.html">Explore the hub <span aria-hidden="true">↗</span></a><a class="button button-outline-light" href="https://givebutter.com/maha-mental-health-gvp1bu" target="_blank" rel="noopener noreferrer">Donate to ICI <span aria-hidden="true">↗</span></a></div></div><div class="hero-index" aria-label="Explore the hub"><div class="index-top"><span>FIELD GUIDE / 001</span><span>FOUR WAYS IN</span></div><a href="evidence.html"><span>01</span><strong>Understand the evidence</strong><b aria-hidden="true">↗</b></a><a href="support.html"><span>02</span><strong>Find support</strong><b aria-hidden="true">↗</b></a><a href="organizations.html"><span>03</span><strong>Meet the organizations</strong><b aria-hidden="true">↗</b></a><a href="policy.html"><span>04</span><strong>Follow public action</strong><b aria-hidden="true">↗</b></a><div class="index-bottom">A PUBLIC RESOURCE FOR PEOPLE, FAMILIES, CLINICIANS & COMMUNITIES</div></div></div><div class="hero-rule shell"><span>KNOWLEDGE</span><span>OPTIONS</span><span>CHOICE</span></div></section>
<section class="section intro-section" id="approach"><div class="shell intro-grid"><div class="section-side"><span class="section-number">01 / THE APPROACH</span><span class="side-rule"></span></div><div class="prose-large"><h2>We need a wider view of <em>mental health.</em></h2><p>Social isolation, economic insecurity, environmental exposures, nutrition, technology, trauma, community disconnection, and the treatments intended to help may all play a role in mental health. We do not yet know the relative contribution of each. No single institution, profession, or movement has all the answers.</p><p>Progress asks for humility, curiosity, rigorous research, and a willingness to question long-standing assumptions. It also asks us to protect access to care and the ability of individuals, families, and clinicians to make informed decisions.</p><div class="approach-note"><strong>Our standard</strong><p>We distinguish what is known, what is debated, and what remains uncertain. We link to the original source, describe its purpose, and revisit resources as evidence changes. Editorial inclusion is separate from financial support; no listing is paid placement or blanket endorsement.</p></div></div></div></section>
<section class="section pathways"><div class="shell"><div class="section-head"><div><span class="section-number">02 / EXPLORE</span><h2>Follow the question <em>you have.</em></h2></div><p>Choose a path and go deeper. The hub brings together existing work rather than asking people to start from scratch.</p></div><div class="route-grid">''' + card('01','LEARN','Evidence & your options','Treatment information, informed consent, drug benefits and risks, withdrawal, and research gaps.','evidence.html') + card('02','CONNECT','Peer & community support','Spaces shaped by shared experience, mutual aid, peer respite, and human connection.','support.html') + card('03','DISCOVER','Organizations doing the work','A directory of groups contributing to informed choice, support, research, and accountability.','organizations.html') + card('04','FOLLOW','Policy & public action','The issues, sources, and organizations involved in changing mental health systems.','policy.html') + '''</div></div></section>
<section class="section urgent-section"><div class="shell urgent-grid"><div class="urgent-symbol" aria-hidden="true"><span>↘</span><span>↗</span></div><div><span class="section-number">A NOTE ON MEDICATION CHANGES</span><h2>Considering a psychiatric drug change?</h2><p>Withdrawal can be difficult and abrupt changes may be dangerous. Start with information about the drug, preparation, and support; discuss decisions with a qualified prescriber who can consider your circumstances.</p><div class="button-row"><a class="button button-dark" href="evidence.html#withdrawal">Learn about withdrawal <span aria-hidden="true">↗</span></a>''' + ext('https://www.theinnercompass.org/prepare','ICI preparation guide') + '''</div></div></div></section>
<section class="section work-section"><div class="shell"><div class="section-head"><div><span class="section-number">03 / WORK WORTH KNOWING</span><h2>The field is already <em>moving.</em></h2></div><p>People and organizations have spent years building expertise, trust, and practical responses. The hub makes their work easier to find and understand.</p></div><div class="work-lines"><a href="organizations.html#informed-choice"><span>01</span><h3>Informed choice & safer tapering</h3><p>Information for careful decisions.</p><b aria-hidden="true">↗</b></a><a href="organizations.html#peer-support"><span>02</span><h3>Peer-led & community support</h3><p>Connection beyond a clinical setting.</p><b aria-hidden="true">↗</b></a><a href="organizations.html#research"><span>03</span><h3>Independent research & accountability</h3><p>Better evidence and transparency.</p><b aria-hidden="true">↗</b></a><a href="organizations.html#approaches"><span>04</span><h3>Emerging non-drug approaches</h3><p>Promising questions, studied carefully.</p><b aria-hidden="true">↗</b></a></div></div></section>
<section class="section closing-cta"><div class="shell closing-grid"><div><span class="section-number">PUT KNOWLEDGE INTO MOTION</span><h2>Help make room for <em>more choice.</em></h2><p>Give through Inner Compass Initiative’s dedicated MAHA Mental Health campaign to support independent education and peer connection.</p></div><a class="button button-cream" href="https://givebutter.com/maha-mental-health-gvp1bu" target="_blank" rel="noopener noreferrer">Donate to ICI <span aria-hidden="true">↗</span></a></div></section>
'''

evidence = '''<section class="page-hero"><div class="shell"><p class="eyebrow">FIELD GUIDE / 01 — LEARN</p><h1>Evidence & <em>your options.</em></h1><p>Understanding a treatment means asking what it may offer, what risks it carries, how strong the evidence is, and what alternatives or additional supports exist.</p></div></section>
<section class="section"><div class="shell page-layout"><aside class="page-aside"><span>ON THIS PAGE</span><a href="#questions">Questions to ask</a><a href="#medicines">Psychiatric drugs</a><a href="#withdrawal">Withdrawal & tapering</a><a href="#beyond">Other approaches</a><a href="#uncertainty">What remains uncertain</a></aside><div class="page-content"><section id="questions"><span class="section-number">START HERE</span><h2>Better information makes <em>better decisions possible.</em></h2><p>People can benefit from existing care and still deserve candid conversations about its limits. Before starting, continuing, changing, or stopping a treatment, ask:</p><ol class="question-list"><li>What benefits are realistic for someone in my situation, and how were they measured?</li><li>What short- and long-term risks or adverse effects are known?</li><li>What is uncertain, and whose experiences may be missing from the research?</li><li>What other forms of support could be used alongside or instead of this option?</li><li>How will we monitor whether this is helping, and what is the plan if it is not?</li></ol></section>
<section id="medicines"><span class="section-number">PSYCHIATRIC DRUGS & INFORMED CONSENT</span><h2>Read the source. <em>Ask the next question.</em></h2><p>FDA-approved labeling describes indications, warnings, adverse reactions, and patient information for specific medicines. Independent resources can help people frame questions about clinical trials, outcomes, and lived experience. Read different kinds of sources together and discuss what applies to you with a qualified professional.</p><div class="link-rows"><a href="https://www.fda.gov/patients/learn-about-your-medicines" target="_blank" rel="noopener noreferrer"><strong>FDA: Learn About Your Medicines</strong><small>Government drug information and Medication Guides</small><span>↗</span></a><a href="https://www.theinnercompass.org/learn" target="_blank" rel="noopener noreferrer"><strong>Inner Compass Initiative: Learn</strong><small>Independent education on psychiatric drugs and diagnoses</small><span>↗</span></a><a href="https://www.benzoinfo.com/informed-consent/" target="_blank" rel="noopener noreferrer"><strong>Benzodiazepine Information Coalition</strong><small>Informed consent and benzodiazepine safety</small><span>↗</span></a></div></section>
<section id="withdrawal"><span class="section-number">WITHDRAWAL & TAPERING</span><h2>Careful change <em>takes preparation.</em></h2><p>Withdrawal symptoms can be mistaken for a return of an underlying condition, and abrupt discontinuation can cause serious harm. The pace and support needed vary by person and medicine. These links are educational starting points, not personal schedules.</p><div class="callout"><strong>Before making a change</strong><p>Learn about the medicine and its withdrawal risks, consider timing and support, and discuss a plan with a prescriber who can respond if symptoms emerge. Do not stop abruptly on the basis of a website.</p></div><div class="link-rows"><a href="https://www.theinnercompass.org/prepare" target="_blank" rel="noopener noreferrer"><strong>ICI Companion Guide: Prepare</strong><small>Readiness, support, and conversations with prescribers</small><span>↗</span></a><a href="https://www.theinnercompass.org/taper" target="_blank" rel="noopener noreferrer"><strong>ICI Companion Guide: Taper</strong><small>Detailed educational material on tapering considerations</small><span>↗</span></a><a href="https://www.nice.org.uk/guidance/ng215/chapter/Recommendations#withdrawing-a-dependence-forming-medicine-or-antidepressant" target="_blank" rel="noopener noreferrer"><strong>NICE guidance on withdrawal</strong><small>Clinical recommendations from the UK</small><span>↗</span></a></div></section>
<section id="beyond"><span class="section-number">A BROADER RANGE OF SUPPORT</span><h2>Care extends beyond <em>one modality.</em></h2><p>Therapy, peer connection, family and community relationships, sleep, nutrition, physical health, and environmental conditions can all matter. The strength of evidence differs by approach and condition; emerging ideas deserve serious study without being presented as universal answers.</p><div class="link-rows"><a href="support.html"><strong>Peer & community support</strong><small>Mutual aid, peer respite, and groups</small><span>↗</span></a><a href="https://www.nccih.nih.gov/health/mental-health" target="_blank" rel="noopener noreferrer"><strong>NIH: Mental health and complementary approaches</strong><small>Federal research information</small><span>↗</span></a><a href="https://www.metabolicmind.org/resources/science/overview/" target="_blank" rel="noopener noreferrer"><strong>Metabolic Mind: Science overview</strong><small>An emerging research area, with open questions</small><span>↗</span></a></div></section>
<section id="uncertainty"><span class="section-number">SCIENTIFIC HUMILITY</span><h2>Uncertainty is <em>useful information.</em></h2><p>Studies may measure short-term symptom change while people care about long-term functioning, relationships, and quality of life. Some populations and adverse experiences are underrepresented. We seek sources that name these limits clearly, and we do not treat a promising hypothesis as a settled result.</p></section></div></div></section>'''

support = '''<section class="page-hero plum-hero"><div class="shell"><p class="eyebrow">FIELD GUIDE / 02 — CONNECT</p><h1>Support begins <em>with connection.</em></h1><p>Shared experience, trusted relationships, and community-based spaces can be meaningful sources of understanding and practical help.</p></div></section><section class="section"><div class="shell"><div class="section-head"><div><span class="section-number">FIND A PLACE TO BEGIN</span><h2>Different kinds of <em>peer support.</em></h2></div><p>These options are distinct. Explore each organization’s approach, availability, costs, eligibility, and community guidelines before deciding what fits.</p></div><div class="editorial-grid"><article><span class="tile-no">01</span><h3>Online community</h3><p>The Inner Compass Exchange is a peer-to-peer space for people exploring psychiatric diagnoses, drugs, withdrawal, and life beyond conventional frameworks.</p>''' + ext('https://exchange.theinnercompass.org/','Explore the Exchange') + '''</article><article><span class="tile-no">02</span><h3>Peer respite</h3><p>Peer respites are voluntary, short-term community settings. Programs vary by location, admission requirements, and the support they offer.</p>''' + ext('https://power2u.org/directory-of-peer-respites/','Find a peer respite') + '''</article><article><span class="tile-no">03</span><h3>Hearing Voices groups</h3><p>Hearing Voices USA lists groups where people can share experiences such as hearing voices and explore what those experiences mean to them.</p>''' + ext('https://www.hearingvoicesusa.org/hvn-usa-groups-list','Find a group') + '''</article><article><span class="tile-no">04</span><h3>Local networks</h3><p>Peer-led organizations and community groups may offer connection close to home. Ask how facilitators are trained, how privacy is handled, and what crisis supports are available.</p><a class="text-link" href="organizations.html#peer-support">Explore organizations <span aria-hidden="true">↗</span></a></article></div><div class="notice"><strong>Choosing a peer space</strong><p>These groups and programs differ in availability, location, privacy practices, and the support they can offer. Check each program’s own information before relying on it for time-sensitive help.</p></div></div></section>'''

organizations = '''<section class="page-hero"><div class="shell"><p class="eyebrow">FIELD GUIDE / 03 — DISCOVER</p><h1>Organizations <em>doing the work.</em></h1><p>Explore a focused group of organizations and programs working on informed choice, treatment safety, peer support, research, and rights.</p></div></section><section class="section"><div class="shell"><div class="directory-intro"><div><span class="section-number">CURATED DIRECTORY</span><h2>Explore by <em>area of work.</em></h2></div><p>This selection follows the organizations and programs identified for review in the hub’s source list. Descriptions are based on each group’s public materials. Inclusion does not claim a formal partnership, ICI endorsement, or eligibility for funding.</p></div><div class="directory-tools"><label class="search-field"><span class="sr-only">Search organizations</span><input id="directory-search" type="search" placeholder="Search organizations or areas of work…"></label><div class="filters" role="group" aria-label="Filter organizations"><button type="button" data-filter="all" aria-pressed="true">All</button><button type="button" data-filter="informed-choice" aria-pressed="false">Informed choice</button><button type="button" data-filter="peer-support" aria-pressed="false">Peer support</button><button type="button" data-filter="research" aria-pressed="false">Research</button><button type="button" data-filter="approaches" aria-pressed="false">New approaches</button><button type="button" data-filter="rights" aria-pressed="false">Rights & policy</button></div></div><p class="result-count" id="result-count" role="status" aria-live="polite"></p><div class="directory-list" id="directory-list"></div><div class="notice"><strong>How to read this directory</strong><p>Each entry identifies the work and why it is relevant to this hub. These are organizations and programs, not a clinician directory. External sites may change; consult their own pages for current activities and terms. Listings are not paid placement, blanket endorsements, or funding commitments.</p></div></div></section>'''

policy = '''<section class="page-hero plum-hero"><div class="shell"><p class="eyebrow">FIELD GUIDE / 04 — FOLLOW</p><h1>Policy & <em>public action.</em></h1><p>Better information matters most when people can use it to ask questions, improve systems, and hold institutions accountable.</p></div></section><section class="section"><div class="shell"><div class="section-head"><div><span class="section-number">AREAS TO WATCH</span><h2>What is changing <em>and why?</em></h2></div><p>Policy varies by state and changes over time. Use primary sources for the current text and status of a bill or rule.</p></div><div class="policy-list"><article><span>01 / CHOICE</span><h3>Informed consent</h3><p>What information do people receive about expected benefits, adverse effects, alternatives, and withdrawal before a treatment decision?</p></article><article><span>02 / SAFETY</span><h3>Drug safety & reporting</h3><p>How are adverse experiences recognized, reported, studied, and communicated to patients and clinicians?</p></article><article><span>03 / EVIDENCE</span><h3>Research transparency</h3><p>Are long-term outcomes, negative findings, and meaningful measures of well-being available to the public?</p></article><article><span>04 / ACCESS</span><h3>More forms of support</h3><p>What barriers affect peer-led, community-based, and non-pharmacological options?</p></article></div><div class="source-panel"><span class="section-number">CHECK THE PRIMARY SOURCE</span><h2>Follow a policy <em>from the record.</em></h2><p>For federal bills, search Congress.gov by keyword or bill number. For federal agency rules, use Regulations.gov to read the text and comment deadlines. For suspected problems with medical products, FDA MedWatch explains how to report.</p><div class="source-links">''' + ext('https://www.congress.gov/','Congress.gov') + ext('https://www.regulations.gov/','Regulations.gov') + ext('https://www.fda.gov/safety/medwatch-fda-safety-information-and-adverse-event-reporting-program','FDA MedWatch') + '''</div><div class="tracking-tool"><div><span class="section-number">FOLLOW LEGISLATION</span><h3>Track bills with Delilah.</h3><p>Delilah lets you search and bookmark bills in Congress and all 50 states, then receive updates. For agency regulations and public comment periods, use Regulations.gov above.</p></div><a class="button button-dark" href="https://delilahusa.com/app" target="_blank" rel="noopener noreferrer">Explore Delilah <span aria-hidden="true">↗</span></a></div><p class="policy-caveat">Check dates and status at the linked primary source before sharing or acting.</p></div></section>'''

giving = '''<section class="page-hero giving-hero"><div class="shell"><p class="eyebrow">GIVE / STRENGTHEN THE FIELD</p><h1>Help make room for <em>better choices.</em></h1><p>Good work in mental health often grows from organizations with deep experience and limited resources. Supporting that work means investing in information, connection, and accountability.</p><a class="button button-cream" href="https://givebutter.com/maha-mental-health-gvp1bu" target="_blank" rel="noopener noreferrer">Donate to ICI <span aria-hidden="true">↗</span></a></div></section><section class="section"><div class="shell giving-grid"><div><span class="section-number">WHY CAPACITY MATTERS</span><h2>Strengthen work that <em>already exists.</em></h2><p>Rather than creating another organization to duplicate the field, the Capacity Fund vision is to help credible groups deepen and sustain their work. Its focus includes informed choice, psychiatric drug safety, peer support, independent research, and policy education.</p><p>Selection standards, decision authority, reporting, and fund administration need to be set before contributions can be solicited for that specific fund. Being listed on this site does not entitle an organization to funding.</p><div class="fund-pillars"><span>01 / Independent education</span><span>02 / Peer & community support</span><span>03 / Research & accountability</span><span>04 / Policy understanding</span></div></div><div class="giving-card" id="give-ici"><span class="section-number">GIVE NOW</span><h3>Support Inner Compass Initiative</h3><p>Inner Compass Initiative (ICI) is an independent 501(c)(3) nonprofit providing public education and peer connection around psychiatric drugs, diagnoses, and withdrawal.</p><a class="button button-plum" href="https://givebutter.com/maha-mental-health-gvp1bu" target="_blank" rel="noopener noreferrer">Donate to ICI <span aria-hidden="true">↗</span></a><p class="donation-clarity">Your donation is made to <strong>Inner Compass Initiative</strong> through ICI’s dedicated MAHA Mental Health campaign. It is not a contribution to a MAHA-managed Capacity Fund. ICI controls its donation processing and receipts.</p></div></div></section><section class="section fund-governance"><div class="shell"><span class="section-number">FOR FUTURE FUNDING</span><h2>A credible fund needs <em>clear safeguards.</em></h2><div class="governance-grid"><div><strong>Defined decisions</strong><p>Review roles, approvals, and conflicts of interest should be established in writing.</p></div><div><strong>Transparent selection</strong><p>Funding decisions should follow documented criteria, separate from editorial inclusion.</p></div><div><strong>Accountable reporting</strong><p>Organizations should describe how funds were used, work completed, challenges, and outcomes.</p></div></div></div></section>'''

pages = [
    ('index.html','Home','A starting point for honest information, support, and choice in mental health.','home',home),
    ('evidence.html','Evidence & Options','Explore mental health evidence, informed consent, psychiatric drugs, withdrawal, and other approaches.','evidence',evidence),
    ('support.html','Peer & Community Support','Explore peer connection, respite, and community-based support.','support',support),
    ('organizations.html','Organizations','Find organizations working on informed choice, peer support, research, and accountability.','organizations',organizations),
    ('policy.html','Policy & Public Action','Follow mental health policy questions and consult primary public sources.','policy',policy),
    ('giving.html','Support the Work','Support independent education and peer connection, and learn about Capacity Fund safeguards.','giving',giving)
]
for filename,title,description,active,body in pages:
    (ROOT / filename).write_text(layout(title,description,active,body),encoding='utf-8')
print('Generated',len(pages),'pages')
